version: '3'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-vue-project
    ports:
      - "80:80"
    restart: always
    networks:
      - app-network
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf
    # ถ้าคุณมี backend API ให้เปิด comment ด้านล่าง
    # depends_on:
    #   - api-server

  # ถ้าคุณมี backend API ให้เปิด comment ด้านล่าง
  # api-server:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   container_name: api-server
  #   ports:
  #     - "3000:3000"
  #   restart: always
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge